config/routes.rb
Rails.application.routes.draw do
  devise_for :applicant_users
  resources :job_applications

  namespace :api do
    namespace :v1 do
      resources :job_lists
      resources :job_applications
      resources :registrations, only: [:create]
      resources :sessions, only: [:create]
      resource :profile, only: [:show, :update]
      patch 'change_password', to: 'change_passwords#update'
    end
  end


  get 'dashboard/index'
  resources :job_lists
  namespace :admin do
      resources :users
      resources :constitutional_governments
      resources :directorates
      resources :natdirectorates
      resources :departments

     

      root to: "users#index"
    end
    
  resources :minister_archives
  resources :constitutional_governments
  resources :user_profiles
  resources :minister_document_forward_department_units
  get 'dashboard_operator_minister/index'
  resources :document_dg_forward_ministers
  resources :minister_document_forward_departments
  resources :minister_document_forward_natdirectorates

  resources :minister_document_forward_directorates
 
  resources :minister_documents do 
    resources :comment_minister_document, as: :comment_minister_documents
  end

  resources :archives
  resources :document_dg_forward_department_units
  get 'dashboard_staff/index'

  resources :document_dg_forward_departments
  get 'dashboard_directorate/index'
  get 'dashboard_directorate/show'
  get 'dashboard_natdirectorate/index'
  get 'dashboard_natdirectorate/show'
  resources :document_dn_forward_departments
  resources :document_from_dns do 
    resources :comment_document_dn, as: :comment_document_dns
  end
  resources :document_from_dgs do 
    resources :comment_document_dg, as: :comment_document_dgs
  end
  resources :document_dg_forward_natdirectorates
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
    # get 'users' => 'devise/password#edit', :as => 'edit_user_password'
  end
  
  get 'dashboard_minister', to: 'dashboard_minister#index', as: 'dashboard_minister'
  get 'dashboard_minister/view_minister_document/:id' , to: 'dashboard_minister#view_minister_document', as: 'view_minister_document' 
  get 'dashboard_minister/document_dg_minister', to: 'dashboard_minister#document_dg_minister', as: 'document_dg_minister'
  get 'dashboard_minister/view_document_from_dg_minister/:id' , to: 'dashboard_minister#view_document_from_dg_minister', as: 'view_document_from_dg_minister' 
  

  get 'dashboard_operator_minister', to: 'dashboard_operator_minister#index', as: 'dashboard_operator_minister'
  get 'dashboard_operator_minister/view_document_from_dg_op_minister/:id' , to: 'dashboard_operator_minister#view_document_from_dg_op_minister', as: 'view_document_from_dg_op_minister' 
  
  
  get 'dashboard_directorate', to: 'dashboard_directorate#index', as: 'dashboard_directorate'
  get 'dashboard_directorate/view_document_dg/:id' , to: 'dashboard_directorate#view_document_dg', as: 'view_document_dg'
  get 'dashboard_directorate/document_dn'
  get 'dashboard_directorate/view_document_dn/:id' , to: 'dashboard_directorate#view_document_dn', as: 'view_document_dn'
  get 'dashboard_directorate/minister_document_dg', to: 'dashboard_directorate#minister_document_dg', as: 'minister_document_dg'
  get 'dashboard_directorate/view_minister_document_dg/:id' , to: 'dashboard_directorate#view_minister_document_dg', as: 'view_minister_document_dg'
  

  get 'dashboard_operator_directorate', to: 'dashboard_operator_directorate#index', as: 'dashboard_operator_directorate'
  get 'dashboard_operator_directorate/view_minister_doc_op_dg/:id' , to: 'dashboard_operator_directorate#view_minister_doc_op_dg', as: 'view_minister_doc_op_dg'
  
  get 'dashboard_natdirectorate', to: 'dashboard_natdirectorate#index', as: 'dashboard_natdirectorate'
  get 'dashboard_natdirectorate/view_doc_dg/:id' , to: 'dashboard_natdirectorate#view_doc_dg', as: 'view_doc_dg'
  get 'dashboard_natdirectorate/doc_from_dn/' , to: 'dashboard_natdirectorate#doc_from_dn', as: 'doc_from_dn'
  get 'dashboard_natdirectorate/view_doc_from_dn/:id' , to: 'dashboard_natdirectorate#view_doc_from_dn', as: 'view_doc_from_dn'
  get 'dashboard_natdirectorate/minister_document_op_dn/' , to: 'dashboard_natdirectorate#minister_document_op_dn', as: 'minister_document_op_dn'
  get 'dashboard_natdirectorate/view_minister_document_op_dn/:id' , to: 'dashboard_natdirectorate#view_minister_document_op_dn', as: 'view_minister_document_op_dn'

  get 'dashboard_department', to: 'dashboard_department#index', as: 'dashboard_department'
  get 'dashboard_department/view_document_from_dg/:id' , to: 'dashboard_department#view_document_from_dg', as: 'view_document_from_dg'
  get 'dashboard_department/dcmt_from_dn/' , to: 'dashboard_department#dcmt_from_dn', as: 'dcmt_from_dn'
  get 'dashboard_department/view_dcmt_from_dn/:id' , to: 'dashboard_department#view_dcmt_from_dn', as: 'view_dcmt_from_dn'
  get 'dashboard_department/minister_document_dep/' , to: 'dashboard_department#minister_document_dep', as: 'minister_document_dep'
  get 'dashboard_department/view_minister_document_dep/:id' , to: 'dashboard_department#view_minister_document_dep', as: 'view_minister_document_dep'

  get 'dashboard_staff', to: 'dashboard_staff#index', as: 'dashboard_staff'
  get 'dashboard_staff/view_doc_dg_by_staff/:id' , to: 'dashboard_staff#view_doc_dg_by_staff', as: 'view_doc_dg_by_staff'
  get 'dashboard_staff/doc_dn/' , to: 'dashboard_staff#doc_dn', as: 'doc_dn'
  get 'dashboard_staff/view_doc_dn/:id' , to: 'dashboard_staff#view_doc_dn', as: 'view_doc_dn'

  get 'help_dashboard', to: 'help_dashboard#index', as: 'help_dashboard'
  
  resources :dashboard_natdirectorate do 
    # get 'natdirectorate_dashboard', to: 'natdirectorate_dashboard#index', as: 'natdirectorate_dashboard'
    get 'view_document_from_dg'
    get 'show'

  end

  
 
  resources :departments
  resources :natdirectorates
  resources :directorates
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/document_from_dn.rb
class DocumentFromDn < ApplicationRecord
  # belongs_to :directorate
  belongs_to :natdirectorate
  has_many :document_dn_forward_departments
  has_many :comment_document_dns, dependent: :destroy

  mount_uploader :attachment_doc_dn, AttachmentDocDnUploader

  enum priority: [:Important, :Urgent,  :Normal]
  after_initialize :set_default_priority, :if => :new_record?
  def set_default_priority
    self.priority ||= :Normal
  end

  enum category: [:Parecer, :Memorandum,  :Proposta, :Ofisiu, :Info]
  after_initialize :set_default_category, :if => :new_record?
  def set_default_category
    self.category ||= :Parecer
  end
  
  enum status: [:'0', :'25',  :'50', :'75', :'100']
  after_initialize :set_default_status, :if => :new_record?
  def set_default_status
    self.status ||= :'0'
  end

  enum forwardstatus: [:'natdirectorate', :'department',  :'section']
  after_initialize :set_default_forwardstatus, :if => :new_record?
  def set_default_forwardstatus
    self.forwardstatus ||= :natdirectorate
  end

  enum document_source: [:'internal',  :'external']
  after_initialize :set_default_document_source, :if => :new_record?
  def set_default_document_source
    self.document_source ||= :internal
  end

  def self.ransackable_attributes(_auth_object = nil)
    [
      "sender",
      "subject",
      "reference_number",
    ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["comment_document_dns", "natdirectorate"]
  end



end

app/controllers/admin/document_from_dns_controller.rb
module Admin
  class DocumentFromDnsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/document_from_dns_controller.rb
class DocumentFromDnsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document_from_dn, only: %i[ show edit update destroy ]
  before_action :set_directorate_id, only: %i[show edit new index update]

  load_and_authorize_resource

  # GET /document_from_dns or /document_from_dns.json
  def index
    @q = DocumentFromDn.where(natdirectorate_id: @natdirectorate_id).order(created_at: :desc).ransack(params[:q])
    @document_from_dns = @q.result(distinct: true).page(params[:page]).per(10)
  end

  # GET /document_from_dns/1 or /document_from_dns/1.json
  def show
    @comment_document_dn = @document_from_dn.comment_document_dns.build
  end

  # GET /document_from_dns/new
  def new
    @document_from_dn = DocumentFromDn.new
  end

  # GET /document_from_dns/1/edit
  def edit
  end

  # POST /document_from_dns or /document_from_dns.json
  def create
    @document_from_dn = DocumentFromDn.new(document_from_dn_params)

    respond_to do |format|
      if @document_from_dn.save
        format.html { redirect_to document_from_dn_url(@document_from_dn), notice: "Document from dn was successfully created." }
        format.json { render :show, status: :created, location: @document_from_dn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document_from_dn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_from_dns/1 or /document_from_dns/1.json
  def update
    respond_to do |format|
      if @document_from_dn.update(document_from_dn_params)
        if current_user&.operator_dn?
          format.html { redirect_to document_from_dn_url(@document_from_dn), notice: "Document from dn was successfully updated." }
          format.json { render :show, status: :ok, location: @document_from_dn } 
        elsif current_user&.department?
          format.html { redirect_to view_dcmt_from_dn_path(@document_from_dn), notice: 'Document was successfully updates.'  }
        elsif current_user&.staff?
          format.html { redirect_to view_doc_dn_path(@document_from_dn), notice: 'Document was successfully updates.'  }
        end
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document_from_dn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_from_dns/1 or /document_from_dns/1.json
  def destroy
    @document_from_dn.destroy!

    respond_to do |format|
      format.html { redirect_to document_from_dns_url, notice: "Document from dn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_from_dn
      @document_from_dn = DocumentFromDn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_from_dn_params
      params.require(:document_from_dn).permit(:sender, :subject, :reference_number, :priority, :category, :status,:document_source,
       :forwardstatus, :attachment_doc_dn, :directorate_id, :natdirectorate_id)
    end

    def set_directorate_id
      @directorate_id = current_user.directorate_id
      @natdirectorate_id = current_user.natdirectorate_id
    end
end

app/helpers/document_from_dns_helper.rb
module DocumentFromDnsHelper
end

app/views/document_from_dns/_document_from_dn.html.erb
<div class="row mt-2">
  <div class="col-sm-8 mb-3 mb-sm-0">
    <div class="card">
    <div class="card-header cardcolor">Document DN</div>
      <div class="card-body">

            <div id="<%= dom_id document_from_dn %>">
              <ul class="list-group">
                  <li class="list-group-item">
                      <div class=" row">
                      <label class="col-sm-3 col-form-label"><strong>Sender:</strong></label> 
                      <div class="col-sm-7">
                        <%= document_from_dn.sender %> 
                      </div>
                      <div class="col-sm-2">
                        <span class="badge text-bg-success rounded-pill float-end"><%= document_from_dn.document_source %></span>
                      </div>
                    </div>
                  </li>

                  <li class="list-group-item">
                      <div class=" row">
                        <label class="col-sm-3 col-form-label"><strong>Subject:</strong></label> 
                        <div class="col-sm-9">
                          <%= document_from_dn.subject %>
                        </div>
                      </div>
                  </li>

                  <li class="list-group-item">
                      <div class=" row">
                        <label class="col-sm-3 col-form-label"><strong>Reference number:</strong></label> 
                        <div class="col-sm-9">
                          <%= document_from_dn.reference_number %>
                        </div>
                      </div>
                  </li>

                  <li class="list-group-item">
                      <div class=" row">
                        <label class="col-sm-3 col-form-label"><strong>Priority:</strong></label> 
                        <div class="col-sm-9">
                          <%= document_from_dn.priority %>
                        </div>
                      </div>
                  </li>

                  <li class="list-group-item">
                      <div class=" row">
                        <label class="col-sm-3 col-form-label"><strong>Category:</strong></label> 
                        <div class="col-sm-9">
                          <%= document_from_dn.category %>
                        </div>
                      </div>
                  </li>

                   <li class="list-group-item">
                <div class="row">
                    <label class="col-sm-3 col-form-label"><strong>Status:</strong></label> 
                  <div class="col-sm-9">


                  <% @sts =  document_from_dn.status.to_i %>
                  <% if @sts == 0 %>
                      <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
                  <% elsif @sts == 100 %>
                      <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
                  <% else %>
                      <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
                  <% end %>

                  <div class="">
                    <div class="row">
                      <div class="col-md-2">
                        <%= @status %><br>
                      </div>
                      <div class=" col-md-10">
                        <div class="progress mt-2" >
                          <div class="progress-bar bg-success" role="progressbar" style="width: <%= @sts %>%;" aria-valuenow="<%= @sts %>" aria-valuemin="<%= @sts %>" aria-valuemax="100"><%= @sts%>%</div>
                        </div>
                      </div>
                    </div>
                  </div>
                   
                  </div>
                </div>
              </li>

                  <li class="list-group-item">
                  <div class=" row">
                       <label class="col-sm-3 col-form-label"><strong>Forward Status:</strong></label> 
                      <div class="col-sm-9">
                      <% fs = document_from_dn.forwardstatus %>
                      <% 
                         if fs == 'natdirectorate'
                            fst = 0
                         elsif fs == 'department'
                            fst = 100
                         end
                       %>


                    <div class="position-relative m-4">
                      <div class="progress  " role="progressbar" aria-label="Progress" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="height: 4px;">
                        <div class="progress-bar bg-success" style="width: <%= fst %>%"></div>
                      </div>

                      <span class="position-absolute top-0 start-0 translate-middle  rounded-pill badge text-bg-secondary" >Nat Directorate</span>
                      <span class="position-absolute top-0 start-100 translate-middle  rounded-pill badge text-bg-success" >Department</span>
                    </div>

                        
                      </div>
                    </div>


              </li>

                  <li class="list-group-item">
                  <div class=" row">
                      <label class="col-sm-3 col-form-label"><strong>Attachment :</strong></label> 
                      <div class="col-sm-9">
                        <a href="<%= document_from_dn.attachment_doc_dn.url %>" target="_blank" %>
                          <%= File.basename(document_from_dn.attachment_doc_dn.file.path) if document_from_dn.attachment_doc_dn.file %>
                        </a>
                      </div>
                    </div>
                  </li>

                </ul>
                <% fs = document_from_dn.forwardstatus %>
                <% if fs == 'natdirectorate' %>
                <%= link_to "Forward", new_document_dn_forward_department_path(doc_id: document_from_dn.id), class:"btn btn-sm btn-secondary mt-2 float-end " %>
                <% end %>
          </div>
       </div>

                


      </div>
  </div>
     
  <div class="col-sm-4">
      <div class="row">

      <div class="col-sm-12 mb-2">
        <div class="card">
        <h6 class="card-header">Update Status</h6>
          <div class="card-body">
            <div class="col-sm-8">
                <% @doc_id = DocumentFromDn.find(params[:id])%>
                   <%= form_with(model: @doc_id) do |form| %>
                      <div class="input-group input-group-sm mb-3">
                        <span class="input-group-text" id="inputGroup-sizing-sm">Status</span>
                        <%= form.select :status, DocumentFromDn.statuses.keys.map {|status| [status.humanize, status]},{}, {class:"form-select form-select-sm",  aria_label:"Sizing example input", aria_describedby:"inputGroup-sizing-sm"} %>                    
                        <%= form.submit "Update", class:"btn btn-sm btn-primary" %>
                      </div>
                  <% end %>
            </div>
          </div>
        </div>
                
      </div>

      <div class="col-sm-12">
        <div class="card">
        <h6 class="card-header">Komentariu</h6>
          <div class="card-body">
           <%= render 'comment_document_dn/comment', document_from_dn: @document_from_dn %>
           <%= render "comment_document_dn/form", document_from_dn: @document_from_dn %>
          </div>
        </div>

      </div>
      </div>
  </div>

</div>

app/views/document_from_dns/_form.html.erb
<div class="col-lg-12">
    <div class="card bg-light">
        <div class="card-body ">
           <div class="mt-5 mt-lg-4">

              <%= form_with(model: document_from_dn) do |form| %>
                <% if document_from_dn.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(document_from_dn.errors.count, "error") %> prohibited this document_from_dn from being saved:</h2>

                    <ul>
                      <% document_from_dn.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                    <div class="mb-2 row">
                      <%= form.label :sender, class:"col-sm-2 col-form-label" %>
                      <div class="col-sm-6">
                        <div class="row">
                          <div class="col-sm-8">
                            <%= form.text_field :sender, class:"form-control" %>
                          </div>
                          <div class="col-sm-4">
                            <%= form.select :document_source, DocumentFromDn.document_sources.keys.map {|document_source| [document_source.humanize, document_source]},{}, {class:"form-select"} %>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="mb-3 row">
                      <%= form.label :subject, class:"col-sm-2 col-form-label" %>
                      <div class="col-sm-5">
                        <%= form.text_field :subject, class:"form-control" %>
                      </div>
                    </div>

                    <div class="mb-3 row">
                      <%= form.label :reference_number, class:"col-sm-2 col-form-label" %>
                      <div class="col-sm-5">
                        <%= form.text_field :reference_number, class:"form-control" %>
                      </div>
                    </div>



                    <div class="mb-3 row">
                      <%= form.label :priority, class:"col-sm-2 col-form-label" %>
                      <div class="col-sm-3">
                        <%= form.select :priority, DocumentFromDn.priorities.keys.map {|priority| [priority.humanize, priority]},{}, {class:"form-select"} %>
                      </div>
                    </div>

                    <div class="mb-3 row">
                      <%= form.label :category, class:"col-sm-2 col-form-label" %>
                      <div class="col-sm-3">
                      <%= form.select :category, DocumentFromDn.categories.keys.map {|category| [category.humanize, category]},{}, {class:"form-select"} %>
                      </div>
                    </div>


                    <div class="mb-3 row">
                      <%= form.label :attachment_doc_dn, class:"col-sm-2 col-form-label" %>
                      <div class="col-sm-3">
                      <%= form.file_field :attachment_doc_dn %>
                    </div>
                    </div>

                    <div>
                      <%= form.hidden_field :directorate_id, value: @directorate_id %>
                      <%= form.hidden_field :natdirectorate_id, value: @natdirectorate_id %>
                    </div>
                
                <div class=" row">
                   <label class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-3">
                      <%= form.submit "Submit", class:"btn btn-sm btn-secondary menu-hover" %>
                      <%= link_to document_from_dns_path, class:" btn btn-sm btn-secondary menu-hover" do %> Cancel<% end %>
                    </div>
                    </div>
                <% end %>


          </div>  
        </div>  
    </div>  
</div>

app/views/document_from_dns/edit.html.erb
<div class="card mt-2">
    <div class="card-header cardcolor"> Edit Document DN </div>
    <div class="card-body">

    <%= render "form", document_from_dn: @document_from_dn %>

    <div>
</div>

app/views/document_from_dns/index.html.erb
  <div class="card mt-2">
    <div class="card-header cardcolor"> Document DN </div>
    <div class="card-body">

    <div class="row g-0">
      <div class="col-6"> <%= link_to "New Document", new_document_from_dn_path, class:"bi bi-plus btn btn-secondary btn-sm menu-hover" %></div>
      <div class="col-sm-6">
        <%= search_form_for @q, url: document_from_dns_path, method: :get do |f| %>
          <div class="input-group mb-3">
          <%= f.search_field :sender_or_subject_or_reference_number_cont, class:"form-control rounded", type:"search", placeholder:"Search" %>
          <%= f.submit "Search", class:"btn btn-outline-success menu-hover" %>
          </div>
        <% end %>
      </div>
    </div>


 


        

      <div id="document_from_dns">
      <% if @document_from_dns.any? %>
      <table class="table table-sm mt-4 table-hover">
            <thead>
              <tr>
                <th scope="col">Subject</th>
                <th scope="col">Sender </th>
                <th scope="col">Reference number</th>
                <th scope="col">Category</th>
                <th scope="col">Priority</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @document_from_dns.each do |document_from_dn| %>
              <tr>
              <td width="20%"><%= link_to  document_from_dn.subject, document_from_dn_path(document_from_dn), 
                    class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
              </td>
                <td width="20%"><%= document_from_dn.sender %></td>
                <td width="20%"><%= document_from_dn.subject %></td>
                <td><%= document_from_dn.reference_number %></td>
                <td><%= document_from_dn.category %></td>
                <td><%= document_from_dn.priority %></td>
                <% @sts =  document_from_dn.status.to_i %>
                <% if @sts == 0 %>
                    <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
                <% elsif @sts == 100 %>
                    <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
                <% else %>
                    <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
                <% end %>


          <td><%= @status %></td>
                <td>
                  <div class="float-end">
                    <div class="btn-group btn-group-sm " role="group" aria-label="Small button group">
                      <%= link_to " ", document_from_dn_path(document_from_dn), class:"bi bi-eye-fill btn btn-sm btn-outline-secondary menu-hover" %>
                      <%= link_to " ", edit_document_from_dn_path(document_from_dn), class:"bi bi-pencil-fill btn btn-sm btn-outline-secondary menu-hover" %>
                       <!-- Button trigger modal -->
                      <button type="button" class="bi bi-trash-fill btn btn-sm btn-outline-secondary menu-hover" data-bs-toggle="modal" data-bs-target="#exampleModal"></button>
                      <!-- Modal -->
                      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="exampleModalLabel">Do you want to delete?</h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              <%= document_from_dn.subject %>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="bi bi-x-circle-fill btn btn-sm btn-outline-secondary menu-hover" data-bs-dismiss="modal"> No</button>
                              <%= button_to " Yes", document_from_dn, method: :delete, class:"bi bi-check-circle-fill btn btn-sm btn-outline-secondary" %>
                            </div>
                          </div>
                        </div>
                      </div>
                      <!-- End Modal-->
                    </div>

                <% fs = document_from_dn.forwardstatus %>
                <% if fs == 'natdirectorate' %>
                <%= link_to " ", new_document_dn_forward_department_path(doc_id: document_from_dn.id), class:"bi bi-share-fill btn btn-sm btn-outline-secondary menu-hover" %>
                <% end %>


                    
                  </div>
                    </td>
                  
                  
              </tr>
            <% end %>
            </tbody>
          </table>

          <% else %>
      <p>No documents found <%= link_to "Back", document_from_dns_path, class:"btn btn-sm btn-outline-secondary" %></p>
      
    <% end %>
<%= paginate @document_from_dns %>

    </div>

  </div>

app/views/document_from_dns/new.html.erb
<div class=" mt-2">

    <div class="card">
    <div class="card-header cardcolor">New Document DN</div>


<%= render "form", document_from_dn: @document_from_dn %>

</div>
</div>

app/views/document_from_dns/show.html.erb
  <%= render @document_from_dn %>