config/routes.rb
Rails.application.routes.draw do
  devise_for :applicant_users
  resources :job_applications

  namespace :api do
    namespace :v1 do
      resources :job_lists
      resources :job_applications
      resources :registrations, only: [:create]
      resources :sessions, only: [:create]
      resource :profile, only: [:show, :update]
      patch 'change_password', to: 'change_passwords#update'
    end
  end


  get 'dashboard/index'
  resources :job_lists
  namespace :admin do
      resources :users
      resources :constitutional_governments
      resources :directorates
      resources :natdirectorates
      resources :departments

     

      root to: "users#index"
    end
    
  resources :minister_archives
  resources :constitutional_governments
  resources :user_profiles
  resources :minister_document_forward_department_units
  get 'dashboard_operator_minister/index'
  resources :document_dg_forward_ministers
  resources :minister_document_forward_departments
  resources :minister_document_forward_natdirectorates

  resources :minister_document_forward_directorates
 
  resources :minister_documents do 
    resources :comment_minister_document, as: :comment_minister_documents
  end

  resources :archives
  resources :document_dg_forward_department_units
  get 'dashboard_staff/index'

  resources :document_dg_forward_departments
  get 'dashboard_directorate/index'
  get 'dashboard_directorate/show'
  get 'dashboard_natdirectorate/index'
  get 'dashboard_natdirectorate/show'
  resources :document_dn_forward_departments
  resources :document_from_dns do 
    resources :comment_document_dn, as: :comment_document_dns
  end
  resources :document_from_dgs do 
    resources :comment_document_dg, as: :comment_document_dgs
  end
  resources :document_dg_forward_natdirectorates
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
    # get 'users' => 'devise/password#edit', :as => 'edit_user_password'
  end
  
  get 'dashboard_minister', to: 'dashboard_minister#index', as: 'dashboard_minister'
  get 'dashboard_minister/view_minister_document/:id' , to: 'dashboard_minister#view_minister_document', as: 'view_minister_document' 
  get 'dashboard_minister/document_dg_minister', to: 'dashboard_minister#document_dg_minister', as: 'document_dg_minister'
  get 'dashboard_minister/view_document_from_dg_minister/:id' , to: 'dashboard_minister#view_document_from_dg_minister', as: 'view_document_from_dg_minister' 
  

  get 'dashboard_operator_minister', to: 'dashboard_operator_minister#index', as: 'dashboard_operator_minister'
  get 'dashboard_operator_minister/view_document_from_dg_op_minister/:id' , to: 'dashboard_operator_minister#view_document_from_dg_op_minister', as: 'view_document_from_dg_op_minister' 
  
  
  get 'dashboard_directorate', to: 'dashboard_directorate#index', as: 'dashboard_directorate'
  get 'dashboard_directorate/view_document_dg/:id' , to: 'dashboard_directorate#view_document_dg', as: 'view_document_dg'
  get 'dashboard_directorate/document_dn'
  get 'dashboard_directorate/view_document_dn/:id' , to: 'dashboard_directorate#view_document_dn', as: 'view_document_dn'
  get 'dashboard_directorate/minister_document_dg', to: 'dashboard_directorate#minister_document_dg', as: 'minister_document_dg'
  get 'dashboard_directorate/view_minister_document_dg/:id' , to: 'dashboard_directorate#view_minister_document_dg', as: 'view_minister_document_dg'
  

  get 'dashboard_operator_directorate', to: 'dashboard_operator_directorate#index', as: 'dashboard_operator_directorate'
  get 'dashboard_operator_directorate/view_minister_doc_op_dg/:id' , to: 'dashboard_operator_directorate#view_minister_doc_op_dg', as: 'view_minister_doc_op_dg'
  
  get 'dashboard_natdirectorate', to: 'dashboard_natdirectorate#index', as: 'dashboard_natdirectorate'
  get 'dashboard_natdirectorate/view_doc_dg/:id' , to: 'dashboard_natdirectorate#view_doc_dg', as: 'view_doc_dg'
  get 'dashboard_natdirectorate/doc_from_dn/' , to: 'dashboard_natdirectorate#doc_from_dn', as: 'doc_from_dn'
  get 'dashboard_natdirectorate/view_doc_from_dn/:id' , to: 'dashboard_natdirectorate#view_doc_from_dn', as: 'view_doc_from_dn'
  get 'dashboard_natdirectorate/minister_document_op_dn/' , to: 'dashboard_natdirectorate#minister_document_op_dn', as: 'minister_document_op_dn'
  get 'dashboard_natdirectorate/view_minister_document_op_dn/:id' , to: 'dashboard_natdirectorate#view_minister_document_op_dn', as: 'view_minister_document_op_dn'

  get 'dashboard_department', to: 'dashboard_department#index', as: 'dashboard_department'
  get 'dashboard_department/view_document_from_dg/:id' , to: 'dashboard_department#view_document_from_dg', as: 'view_document_from_dg'
  get 'dashboard_department/dcmt_from_dn/' , to: 'dashboard_department#dcmt_from_dn', as: 'dcmt_from_dn'
  get 'dashboard_department/view_dcmt_from_dn/:id' , to: 'dashboard_department#view_dcmt_from_dn', as: 'view_dcmt_from_dn'
  get 'dashboard_department/minister_document_dep/' , to: 'dashboard_department#minister_document_dep', as: 'minister_document_dep'
  get 'dashboard_department/view_minister_document_dep/:id' , to: 'dashboard_department#view_minister_document_dep', as: 'view_minister_document_dep'

  get 'dashboard_staff', to: 'dashboard_staff#index', as: 'dashboard_staff'
  get 'dashboard_staff/view_doc_dg_by_staff/:id' , to: 'dashboard_staff#view_doc_dg_by_staff', as: 'view_doc_dg_by_staff'
  get 'dashboard_staff/doc_dn/' , to: 'dashboard_staff#doc_dn', as: 'doc_dn'
  get 'dashboard_staff/view_doc_dn/:id' , to: 'dashboard_staff#view_doc_dn', as: 'view_doc_dn'

  get 'help_dashboard', to: 'help_dashboard#index', as: 'help_dashboard'
  
  resources :dashboard_natdirectorate do 
    # get 'natdirectorate_dashboard', to: 'natdirectorate_dashboard#index', as: 'natdirectorate_dashboard'
    get 'view_document_from_dg'
    get 'show'

  end

  
 
  resources :departments
  resources :natdirectorates
  resources :directorates
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_directorate_id, only: %i[index ]
  before_action :set_goverment_constitutional, only: %i[index ]

  def index
    if (current_user&.minister? or current_user&.operator_minister?)
      @minister_documents = MinisterDocument.where(constitutional_government_id: @constitutional_government_id).order(created_at: :desc).limit(5)
      # @document_from_dgs = DocumentFromDg.order(created_at: :desc).limit(5)
      @document_from_dgs = DocumentFromDg
          .joins(:document_dg_forward_ministers)
          .where(document_dg_forward_ministers: { document_from_dg_id: DocumentFromDg.select(:id) })
          .distinct.order(created_at: :desc).limit(5)

    elsif (current_user&.operator_dg? or current_user&.directorate?)
      @minister_documents = MinisterDocument.joins(minister_document_forward_directorates: :minister_document_directorates)
         .where(minister_document_forward_directorates: {minister_document_id: MinisterDocument.select(:id)})
         .where(minister_document_directorates: {minister_document_forward_directorate_id: MinisterDocumentForwardDirectorate.select(:id)})
         .where(minister_document_directorates: {directorate_id: @directorate_id})
         .distinct.order(created_at: :desc).limit(5)
      
       @document_from_dgs = DocumentFromDg.where(directorate_id: @directorate_id).limit(5)
       @document_from_dns = DocumentFromDn.where(directorate_id: @directorate_id).limit(5)

    elsif (current_user&.operator_dn? or current_user&.natdirectorate?)
      @minister_documents = MinisterDocument.joins(minister_document_forward_natdirectorates: :minister_document_natdirectorates)
      .where(minister_document_forward_natdirectorates: {minister_document_id: MinisterDocument.select(:id)})
      .where(minister_document_natdirectorates: {minister_document_forward_natdirectorate_id: MinisterDocumentForwardNatdirectorate.select(:id)})
      .where(minister_document_natdirectorates: {natdirectorate_id: @natdirectorate_id})
      .distinct.order(created_at: :desc).limit(5)
      
      @document_from_dgs = DocumentFromDg.where(directorate_id: @directorate_id).limit(5)
      @document_from_dns = DocumentFromDn.where(directorate_id: @directorate_id).limit(5)

    elsif (current_user&.department? or current_user&.staff?)
      if @directorate_units.present?
        @minister_documents = MinisterDocument.joins(minister_document_forward_department_units: :minister_document_department_units)
         .where(minister_document_forward_department_units: {minister_document_id: MinisterDocument.select(:id)})
         .where(minister_document_department_units: {minister_document_forward_department_unit_id: MinisterDocumentForwardDepartmentUnit.select(:id)})
         .where(minister_document_department_units: {department_id: @department_id})
         .distinct.order(created_at: :desc).limit(5)
      else
      @minister_documents = MinisterDocument.joins(minister_document_forward_departments: :minister_document_departments)
         .where(minister_document_forward_departments: {minister_document_id: MinisterDocument.select(:id)})
         .where(minister_document_departments: {minister_document_forward_department_id: MinisterDocumentForwardDepartment.select(:id)})
         .where(minister_document_departments: {department_id: @department_id})
         .distinct.order(created_at: :desc).limit(5)
      end
      
      @document_from_dgs = DocumentFromDg.where(directorate_id: @directorate_id).limit(5)
      @document_from_dns = DocumentFromDn.where(directorate_id: @directorate_id).limit(5)
    
    else
      @document_from_dgs = DocumentFromDg.where(directorate_id: @directorate_id).limit(5)
      @document_from_dns = DocumentFromDn.where(directorate_id: @directorate_id).limit(5)
    end

  end

  private
  def set_directorate_id
    @directorate_id = current_user.directorate_id
    @natdirectorate_id = current_user.natdirectorate_id
    @department_id = current_user.department_id
    @directorate_units = Directorate.where(id: @directorate_id ,unit: true)
  end

  def set_goverment_constitutional
    @constitutional_government_id = ConstitutionalGovernment.find_by(active: true)
  end 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard_directorate_page.html.erb




<div class="card mt-1">
  <div class="card-header cardcolor">
    <h5>Recent Minister Documents</h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
            <th scope="col">Subject</th>
            <th scope="col">Sender</th>
            <th scope="col">Reference number</th>
            <th scope="col">status</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
            <% @minister_documents.each do |minister_document| %>
            <tr>
                <td width="20%"><%= link_to  minister_document.subject, view_minister_document_dg_path(minister_document), 
                    class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
                </td>
                <td class="w-25"><%= minister_document.sender %></td>
                <td><%= minister_document.reference_number %></td>
                <% @sts =  minister_document.status.to_i %>
                <% if @sts == 0 %>
                    <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
                <% elsif @sts == 100 %>
                    <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
                <% else %>
                    <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
                <% end %>
                <td><%= @status %></td>
                <td> <%= link_to " ", view_minister_document_dg_path(minister_document), class:"bi bi-eye btn btn-sm btn-outline-primary menu-hover" %></td>
                  
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>

<div class="card mt-1">
  <div class="card-header cardcolor">
    <h5>Recent Document From DG</h5>  
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Subject</th>
        <th scope="col">Sender</th>
        <th scope="col">Reference number</th>
        <th scope="col">status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @document_from_dgs.each do |document_from_dg| %>
        <tr>
            <td width="20%"><%= link_to  document_from_dg.subject, view_document_dg_path(document_from_dg), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
            </td>
        
            <td class="w-25"><%= document_from_dg.sender %></td>
            <td><%= document_from_dg.reference_number %></td>
            <% @sts =  document_from_dg.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to " ", view_document_dg_path(document_from_dg), class:"bi bi-eye btn btn-sm btn-outline-primary menu-hover" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>



<div class="card mt-2">
  <div class="card-header cardcolor">
    <h5>Recent Document From DN</h5>
  </div>
  <div class="card-body">
  <table class="table table-sm table-hover">
  <thead>
      <tr>
      <th scope="col">Subject</th>
      <th scope="col">Sender</th>
      <th scope="col">Reference number</th>
      <th scope="col">status</th>
      <th scope="col"></th>
      </tr>
  </thead>
  <tbody>
  <% @document_from_dns.each do |document_from_dn| %>
      <tr>
        <td width="20%"><%= link_to  document_from_dn.subject, view_document_dn_path(document_from_dn), 
            class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
        </td>
      
          <td class="w-25"><%= document_from_dn.sender %></td>
          <td><%= document_from_dn.reference_number %></td>
          <% @sts =  document_from_dn.status.to_i %>
          <% if @sts == 0 %>
              <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
          <% elsif @sts == 100 %>
              <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
          <% else %>
              <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
          <% end %>
          <td><%= @status %></td>
          <td> <%= link_to " ", view_document_dn_path(document_from_dn), class:"bi bi-eye btn btn-sm btn-outline-primary menu-hover" %></td>
    
      </tr>
<% end %>
  </tbody>
  </table>
    </div>
</div>

app/views/home/_dashboard_natdirectorate_page.html.erb
<div class="card mt-1">
  <div class="card-header cardcolor">
    <h5>Recent Minister Document</h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Subject</th>
        <th scope="col">Sender</th>
        <th scope="col">Reference number</th>
        <th scope="col">status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @minister_documents.each do |minister_document| %>
        <tr>
            <td width="20%"><%= link_to  minister_document.subject, view_minister_document_op_dn_path(minister_document), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
            </td>
        
            <td class="w-25"><%= minister_document.sender %></td>
            <td><%= minister_document.reference_number %></td>
            <% @sts =  minister_document.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to " ", view_minister_document_op_dn_path(minister_document), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>


<div class="card mt-1">
  <div class="card-header cardcolor">
    <h5>Recent Document from DG </h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Subject</th>
        <th scope="col">Sender</th>
        <th scope="col">Reference number</th>
        <th scope="col">status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @document_from_dgs.each do |document_from_dg| %>
        <tr>
            <td width="20%"><%= link_to  document_from_dg.subject, view_doc_dg_path(document_from_dg), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
            </td>
            <td class="w-25"><%= document_from_dg.sender %></td>
            <td><%= document_from_dg.reference_number %></td>
            <% @sts =  document_from_dg.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to " ", view_doc_dg_path(document_from_dg), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>


<div class="card mt-2">
  <div class="card-header cardcolor">
    <h5>Recent Document From DN</h5>
  </div>
  <div class="card-body">
  <table class="table table-sm table-hover">
  <thead>
      <tr>
      <th scope="col">Subject</th>
      <th scope="col">Sender</th>
      <th scope="col">Reference number</th>
      <th scope="col">status</th>
      <th scope="col"></th>
      </tr>
  </thead>
  <tbody>
  <% @document_from_dns.each do |document_from_dn| %>
      <tr>
        <td width="20%"><%= link_to  document_from_dn.subject, view_document_dn_path(document_from_dn), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
        </td>
          <td class="w-25"><%= document_from_dn.sender %></td>
          <td><%= document_from_dn.reference_number %></td>
          <% @sts =  document_from_dn.status.to_i %>
          <% if @sts == 0 %>
              <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
          <% elsif @sts == 100 %>
              <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
          <% else %>
              <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
          <% end %>
          <td><%= @status %></td>
          <td> <%= link_to " ", view_document_dn_path(document_from_dn), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %></td>
    
      </tr>
<% end %>
  </tbody>
  </table>
    </div>
</div>

app/views/home/_department_page.html.erb
<div class="card mt-1">
  <div class="card-header cardcolor">
    <h5>Recent Minister Document</h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Subject</th>
        <th scope="col">Sender</th>
        <th scope="col">Reference number</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @minister_documents.each do |minister_document| %>
        <tr>
            <td width="20%"><%= link_to  minister_document.subject, view_minister_document_dep_path(minister_document), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
            </td>
            <td class="w-25"><%= minister_document.sender %></td>
            <td><%= minister_document.reference_number %></td>
            <% @sts =  minister_document.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to " ", view_minister_document_dep_path(minister_document), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>


<div class="card mt-1">
  <div class="card-header cardcolor">
    <h5>Recent Document from DG </h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Subject</th>
        <th scope="col">Sender</th>
        <th scope="col">Reference number</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @document_from_dgs.each do |document_from_dg| %>
        <tr>
            <td width="20%"><%= link_to  document_from_dg.subject, view_doc_dg_path(document_from_dg), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
            </td>
            <td class="w-25"><%= document_from_dg.sender %></td>
            <td><%= document_from_dg.reference_number %></td>
            <% @sts =  document_from_dg.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to " ", view_doc_dg_path(document_from_dg), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>

<% if !@directorate_units.present? %>

<div class="card mt-2">
  <div class="card-header cardcolor">
    <h5>Recent Document From DN</h5>
  </div>
  <div class="card-body">
  <table class="table table-sm table-hover">
  <thead>
      <tr>
      <th scope="col">Subject</th>
      <th scope="col">Sender</th>
      <th scope="col">Reference number</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      </tr>
  </thead>
  <tbody>
  <% @document_from_dns.each do |document_from_dn| %>
      <tr>
        <td width="20%"><%= link_to  document_from_dn.subject, view_document_dn_path(document_from_dn), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
            </td>
          <td class="w-25"><%= document_from_dn.sender %></td>
          <td><%= document_from_dn.reference_number %></td>
          <% @sts =  document_from_dn.status.to_i %>
          <% if @sts == 0 %>
              <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
          <% elsif @sts == 100 %>
              <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
          <% else %>
              <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
          <% end %>
          <td><%= @status %></td>
          <td> <%= link_to " ", view_document_dn_path(document_from_dn), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %></td>
    
      </tr>
<% end %>
  </tbody>
  </table>
    </div>
<% end %>

</div>

app/views/home/_natdirectorate_page.html.erb
<div class="card mt-1">
  <div class="card-header">
    <h5>Recent Document From DG</h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Sender</th>
        <th scope="col">Subject</th>
        <th scope="col">Reference number</th>
        <th scope="col">status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @document_from_dgs.each do |document_from_dg| %>
        <tr>
        
            <td class="w-25"><%= document_from_dg.sender %></td>
            <td class="w-25"><%= document_from_dg.subject %></td>
            <td><%= document_from_dg.reference_number %></td>
            <% @sts =  document_from_dg.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to "View", document_from_dg_path(document_from_dg), class:"btn btn-sm btn-outline-primary" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>





<div class="card mt-1">
  <div class="card-header">
    <h5>Recent Document From DG</h5>
  </div>
  <div class="card-body">
    <table class="table table-sm table-hover">
    <thead>
        <tr>
        <th scope="col">Sender</th>
        <th scope="col">Subject</th>
        <th scope="col">Reference number</th>
        <th scope="col">status</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% @document_from_dgs.each do |document_from_dg| %>
        <tr>
        
            <td class="w-25"><%= document_from_dg.sender %></td>
            <td class="w-25"><%= document_from_dg.subject %></td>
            <td><%= document_from_dg.reference_number %></td>
            <% @sts =  document_from_dg.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>
            <td><%= @status %></td>
            <td> <%= link_to "View", document_from_dg_path(document_from_dg), class:"btn btn-sm btn-outline-primary" %></td>
      
        </tr>
  <% end %>
    </tbody>
    </table>
    </div>
</div>