config/routes.rb
Rails.application.routes.draw do
  devise_for :applicant_users
  resources :job_applications

  namespace :api do
    namespace :v1 do
      resources :job_lists
      resources :job_applications
      resources :registrations, only: [:create]
      resources :sessions, only: [:create]
      resource :profile, only: [:show, :update]
      patch 'change_password', to: 'change_passwords#update'
    end
  end


  get 'dashboard/index'
  resources :job_lists
  namespace :admin do
      resources :users
      resources :constitutional_governments
      resources :directorates
      resources :natdirectorates
      resources :departments

     

      root to: "users#index"
    end
    
  resources :minister_archives
  resources :constitutional_governments
  resources :user_profiles
  resources :minister_document_forward_department_units
  get 'dashboard_operator_minister/index'
  resources :document_dg_forward_ministers
  resources :minister_document_forward_departments
  resources :minister_document_forward_natdirectorates

  resources :minister_document_forward_directorates
 
  resources :minister_documents do 
    resources :comment_minister_document, as: :comment_minister_documents
  end

  resources :archives
  resources :document_dg_forward_department_units
  get 'dashboard_staff/index'

  resources :document_dg_forward_departments
  get 'dashboard_directorate/index'
  get 'dashboard_directorate/show'
  get 'dashboard_natdirectorate/index'
  get 'dashboard_natdirectorate/show'
  resources :document_dn_forward_departments
  resources :document_from_dns do 
    resources :comment_document_dn, as: :comment_document_dns
  end
  resources :document_from_dgs do 
    resources :comment_document_dg, as: :comment_document_dgs
  end
  resources :document_dg_forward_natdirectorates
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
    # get 'users' => 'devise/password#edit', :as => 'edit_user_password'
  end
  
  get 'dashboard_minister', to: 'dashboard_minister#index', as: 'dashboard_minister'
  get 'dashboard_minister/view_minister_document/:id' , to: 'dashboard_minister#view_minister_document', as: 'view_minister_document' 
  get 'dashboard_minister/document_dg_minister', to: 'dashboard_minister#document_dg_minister', as: 'document_dg_minister'
  get 'dashboard_minister/view_document_from_dg_minister/:id' , to: 'dashboard_minister#view_document_from_dg_minister', as: 'view_document_from_dg_minister' 
  

  get 'dashboard_operator_minister', to: 'dashboard_operator_minister#index', as: 'dashboard_operator_minister'
  get 'dashboard_operator_minister/view_document_from_dg_op_minister/:id' , to: 'dashboard_operator_minister#view_document_from_dg_op_minister', as: 'view_document_from_dg_op_minister' 
  
  
  get 'dashboard_directorate', to: 'dashboard_directorate#index', as: 'dashboard_directorate'
  get 'dashboard_directorate/view_document_dg/:id' , to: 'dashboard_directorate#view_document_dg', as: 'view_document_dg'
  get 'dashboard_directorate/document_dn'
  get 'dashboard_directorate/view_document_dn/:id' , to: 'dashboard_directorate#view_document_dn', as: 'view_document_dn'
  get 'dashboard_directorate/minister_document_dg', to: 'dashboard_directorate#minister_document_dg', as: 'minister_document_dg'
  get 'dashboard_directorate/view_minister_document_dg/:id' , to: 'dashboard_directorate#view_minister_document_dg', as: 'view_minister_document_dg'
  

  get 'dashboard_operator_directorate', to: 'dashboard_operator_directorate#index', as: 'dashboard_operator_directorate'
  get 'dashboard_operator_directorate/view_minister_doc_op_dg/:id' , to: 'dashboard_operator_directorate#view_minister_doc_op_dg', as: 'view_minister_doc_op_dg'
  
  get 'dashboard_natdirectorate', to: 'dashboard_natdirectorate#index', as: 'dashboard_natdirectorate'
  get 'dashboard_natdirectorate/view_doc_dg/:id' , to: 'dashboard_natdirectorate#view_doc_dg', as: 'view_doc_dg'
  get 'dashboard_natdirectorate/doc_from_dn/' , to: 'dashboard_natdirectorate#doc_from_dn', as: 'doc_from_dn'
  get 'dashboard_natdirectorate/view_doc_from_dn/:id' , to: 'dashboard_natdirectorate#view_doc_from_dn', as: 'view_doc_from_dn'
  get 'dashboard_natdirectorate/minister_document_op_dn/' , to: 'dashboard_natdirectorate#minister_document_op_dn', as: 'minister_document_op_dn'
  get 'dashboard_natdirectorate/view_minister_document_op_dn/:id' , to: 'dashboard_natdirectorate#view_minister_document_op_dn', as: 'view_minister_document_op_dn'

  get 'dashboard_department', to: 'dashboard_department#index', as: 'dashboard_department'
  get 'dashboard_department/view_document_from_dg/:id' , to: 'dashboard_department#view_document_from_dg', as: 'view_document_from_dg'
  get 'dashboard_department/dcmt_from_dn/' , to: 'dashboard_department#dcmt_from_dn', as: 'dcmt_from_dn'
  get 'dashboard_department/view_dcmt_from_dn/:id' , to: 'dashboard_department#view_dcmt_from_dn', as: 'view_dcmt_from_dn'
  get 'dashboard_department/minister_document_dep/' , to: 'dashboard_department#minister_document_dep', as: 'minister_document_dep'
  get 'dashboard_department/view_minister_document_dep/:id' , to: 'dashboard_department#view_minister_document_dep', as: 'view_minister_document_dep'

  get 'dashboard_staff', to: 'dashboard_staff#index', as: 'dashboard_staff'
  get 'dashboard_staff/view_doc_dg_by_staff/:id' , to: 'dashboard_staff#view_doc_dg_by_staff', as: 'view_doc_dg_by_staff'
  get 'dashboard_staff/doc_dn/' , to: 'dashboard_staff#doc_dn', as: 'doc_dn'
  get 'dashboard_staff/view_doc_dn/:id' , to: 'dashboard_staff#view_doc_dn', as: 'view_doc_dn'

  get 'help_dashboard', to: 'help_dashboard#index', as: 'help_dashboard'
  
  resources :dashboard_natdirectorate do 
    # get 'natdirectorate_dashboard', to: 'natdirectorate_dashboard#index', as: 'natdirectorate_dashboard'
    get 'view_document_from_dg'
    get 'show'

  end

  
 
  resources :departments
  resources :natdirectorates
  resources :directorates
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/controllers/dashboard_natdirectorate_controller.rb
class DashboardNatdirectorateController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document_from_dg, only: %i[ show view_doc_dg]
  before_action :set_directorate_id, only: %i[index view_doc_dg doc_from_dn view_doc_from_dn minister_document_op_dn]
  before_action :set_userid, only: %i[index  view_doc_dg doc_from_dn view_doc_from_dn] 
  before_action :set_minister_document_id, only: %i[view_minister_document_op_dn ]

  def index
    @q = DocumentFromDg
      .joins(document_dg_forward_natdirectorates: :document_dg_natdirectorates)
      .where(document_dg_forward_natdirectorates: { document_from_dg_id: DocumentFromDg.select(:id) })
      .where(document_dg_natdirectorates: { document_dg_forward_natdirectorate_id: DocumentDgForwardNatdirectorate.select(:id) })
      .where(document_dg_natdirectorates: {natdirectorate_id: @natdirectorate_id})
      .distinct
      .order(created_at: :desc)
      .ransack(params[:q])

    @document_from_dgs = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def doc_from_dn 
    @q = DocumentFromDn.where(natdirectorate_id: @natdirectorate_id).ransack(params[:q])
    @document_from_dns =  @q.result(distinct: true).page(params[:page]).per(10)
  end

  def minister_document_op_dn
    @q = MinisterDocument.joins(minister_document_forward_natdirectorates: :minister_document_natdirectorates)
         .where(minister_document_forward_natdirectorates: {minister_document_id: MinisterDocument.select(:id)})
         .where(minister_document_natdirectorates: {minister_document_forward_natdirectorate_id: MinisterDocumentForwardNatdirectorate.select(:id)})
         .where(minister_document_natdirectorates: {natdirectorate_id: @natdirectorate_id})
         .distinct
         .order(created_at: :desc)
         .ransack(params[:q])

    @minister_documents = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def view_minister_document_op_dn
    @comment_minister_document = @minister_document.comment_minister_documents.build
  end 

  def view_doc_from_dn 
    @document_from_dn = DocumentFromDn.find(params[:id])
    @comment_document_dn = @document_from_dn.comment_document_dns.build

    @document_dn_forward_department = DocumentDnForwardDepartment.find_by(document_from_dn_id: @document_from_dn)
    @document_dn_departments = DocumentDnDepartment.where(document_dn_forward_department_id: @document_dn_forward_department)

  end

  def show
  end

  def view_doc_dg
    @comment_document_dg = @document_from_dg.comment_document_dgs.build
  end

  private
  def set_directorate_id
    @directorate_id = current_user.directorate_id
    @natdirectorate_id = current_user.natdirectorate_id
    @natdirectorate = Natdirectorate.find_by(id: @natdirectorate_id)
  end

  def set_document_from_dg
    @document_from_dg = DocumentFromDg.find(params[:id])
    @document_from_dg_forward_natdirectorate = DocumentDgForwardNatdirectorate.find_by(document_from_dg_id: @document_from_dg )
    @document_from_dg_natdirectorates = DocumentDgNatdirectorate.where(document_dg_forward_natdirectorate_id: @document_from_dg_forward_natdirectorate )
    @document_dg_forward_department = DocumentDgForwardDepartment.find_by(document_from_dg_id: @document_from_dg)
    @document_dg_departments = DocumentDgDepartment.where(document_dg_forward_department_id: @document_dg_forward_department)
  end

  def set_minister_document_id
    @minister_document_forward_natdirectorate = MinisterDocumentForwardNatdirectorate.find_by(minister_document_id: params[:id])
    @minister_document = MinisterDocument.find_by(id: @minister_document_forward_natdirectorate.minister_document_id)
    @directorate_id = current_user.directorate_id
    @natdirectorate_id = current_user.natdirectorate_id
    @minister_document_forward_directorate = MinisterDocumentForwardDirectorate.find_by(minister_document_id: @minister_document )
    @minister_document_forward_natdirectorates = MinisterDocumentForwardNatdirectorate.find_by(minister_document_id: @minister_document, directorate_id: @directorate_id )
    @minister_document_forward_departments = MinisterDocumentForwardDepartment.find_by(minister_document_id: @minister_document, natdirectorate_id: @natdirectorate_id )
    @minister_document_departments = MinisterDocumentDepartment.where(minister_document_forward_department_id: @minister_document_forward_departments)
  end

  def set_userid
    @user_id = current_user.id
    @app_userid = User.find_by(id: @user_id) 
   @natdirectorate = Natdirectorate.find_by(id:  @app_userid.natdirectorate_id)

  end 
end

app/helpers/dashboard_natdirectorate_helper.rb
module DashboardNatdirectorateHelper
end

app/views/dashboard_natdirectorate/doc_from_dn.html.erb
  <div class="card mt-2">
    <div class="card-header cardcolor">
      Document From DN
    </div>
    <div class="card-body">

    <div class="row g-0">

     <div class="col-sm-6">
        <%= search_form_for @q, url: doc_from_dn_path do |f| %>
          <div class="input-group mb-3">
          <%= f.search_field :sender_or_subject_or_reference_number_cont, class:"form-control rounded", type:"search", placeholder:"Search" %>
          <%= f.submit "Search", class:"btn btn-outline-secondary menu-hover" %>
          </div>
        <% end %>
      </div>
    </div>
 

<div id="document_from_dns">
<% if @document_from_dns.any? %>
 <table class="table table-sm mt-4 table-hover">
      <thead>
        <tr>
          <th scope="col">Subject</th>
          <th scope="col">Sender </th>
          <th scope="col">Reference number</th>
          <th scope="col">Category</th>
          <th scope="col">Priority</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @document_from_dns.each do |document_from_dn| %>
        <tr>
          <td width="20%"><%= link_to  document_from_dn.subject, view_doc_from_dn_path(document_from_dn), 
                class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
          </td>
          <td width="20%"><%= document_from_dn.sender %></td>
          <td><%= document_from_dn.reference_number %></td>
          <td><%= document_from_dn.category %></td>
          <td><%= document_from_dn.priority %></td>
           
            <% @sts =  document_from_dn.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>


          <td><%= @status %></td>
          <td>
            <div class="float-end">
                <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                  <%= link_to " ", view_doc_from_dn_path(document_from_dn), class:"bi bi-eye-fill btn btn-sm btn-outline-primary menu-hover" %>
                </div>
              <% if current_user&.operator_dn?  %>
               <%= link_to "Forward", new_document_dn_forward_department_path(doc_id: document_from_dn.id), class:"bi bi-share-fill btn btn-sm btn-secondary menu-hover" %>
              <% end %>
          </td>
             
            
        </tr>
      <% end %>
      </tbody>
    </table>
   
    <%= paginate @document_from_dns %>

  <% else %>
      <p>No documents found <%= link_to "Back", doc_from_dn_path, class:"btn btn-sm btn-outline-secondary menu-hover" %></p>
   <% end %>
    </div>

  </div>

app/views/dashboard_natdirectorate/index.html.erb
  <div class="card mt-2">
    <div class="card-header cardcolor">
      Document From DG 
    </div>
    <div class="card-body">

    <div class="row g-0">

      
      <div class="col-sm-6">
        <%= search_form_for @q, url: dashboard_natdirectorate_path do |f| %>
          <div class="input-group mb-3">
          <%= f.search_field :sender_or_subject_or_reference_number_cont, class:"form-control form-control-sm rounded", type:"search", placeholder:"Search" %>
          <%= f.submit "Search", class:"btn btn-sm btn-outline-secondary menu-hover" %>
          </div>
        <% end %>
      </div>
    </div>

<div id="document_from_dgs">
<% if @document_from_dgs.any? %>
 <table class="table table-sm mt-4 table-hover">
      <thead>
        <tr>
          <th scope="col">Subject</th>
          <th scope="col">Sender </th>
          <th scope="col">Reference number</th>
          <th scope="col">Category</th>
          <th scope="col">Priority</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @document_from_dgs.each do |document_from_dg| %>
        <tr>
        <td width="20%"><%= link_to  document_from_dg.subject, view_doc_dg_path(document_from_dg), 
              class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
        </td>
          <td width="20%"><%= document_from_dg.sender %></td>
          <td><%= document_from_dg.reference_number %></td>
          <td><%= document_from_dg.category %></td>
          <td><%= document_from_dg.priority %></td>
           
            <% @sts =  document_from_dg.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
            <% end %>

          <td><%= @status %></td>
          <td>
            <div class="float-end">
                <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                  <%= link_to " ", view_doc_dg_path(document_from_dg), class:"bi bi-eye-fill btn btn-sm btn-outline-secondary menu-hover" %>
                </div>
              <% if current_user&.operator_dn?  %>
                <% fs = document_from_dg.forwardstatus %>
                  <% if fs != 'department' %>
                  <%= link_to "Forward", new_document_dg_forward_department_path(doc_id: document_from_dg.id), class:"bi bi-share-fill btn btn-sm btn-secondary menu-hover" %>
                  <% end %>
               <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @document_from_dgs %>
  <% else %>
      <p>No documents found <%= link_to "Back", dashboard_natdirectorate_path, class:"btn btn-sm btn-outline-secondary" %></p>
   <% end %>
    </div>

  </div>

app/views/dashboard_natdirectorate/minister_document_op_dn.html.erb



  <div class="card mt-2">
    <div class="card-header cardcolor">
      Minister Documents
    </div>
    <div class="card-body">

    <div class="row g-0">
     
      <div class="col-sm-6">
        <%= search_form_for @q, url: dashboard_operator_directorate_path, method: :get do |f| %>
          <div class="input-group mb-3">
          <%= f.search_field :sender_or_subject_or_reference_number_cont, class:"form-control form-control-sm rounded", type:"search", placeholder:"Search" %>
          <%= f.submit "Search", class:"btn btn-sm btn-outline-secondary menu-hover" %>
          </div>
        <% end %>
      </div>
    </div>

  

<div id="minister_documents">
<% if @minister_documents.any? %>
 <table class="table table-sm mt-4 table-hover">
      <thead>
        <tr>
          <th scope="col">Subject</th>
          <th scope="col">Sender </th>
          <th scope="col">Reference number</th>
          <th scope="col">Category</th>
          <th scope="col">Priority</th>
          <th scope="col">Status</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @minister_documents.each do |minister_document| %>
        <tr>
        <td width="20%"><%= link_to  minister_document.subject, view_minister_document_op_dn_path(minister_document), 
              class:"link-offset-1 link-offset-1-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
        </td>
          <td width="20%"><%= minister_document.sender %></td>
          <td><%= minister_document.reference_number %></td>
          <td><%= minister_document.category %></td>
          <td><%= minister_document.priority %></td>
           
            <% @sts =  minister_document.status.to_i %>
            <% if @sts == 0 %>
                <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
            <% elsif @sts == 100 %>
                <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
            <% else %>
                <% @status = "<span class='badge rounded-pill bg-warning'>In Progress</span>".html_safe %>
            <% end %>


          <td><%= @status %></td>
          <td>
            <div class="float-end">
                <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                  <%= link_to " ", view_minister_document_op_dn_path(minister_document), class:"bi bi-eye-fill btn btn-sm btn-outline-secondary menu-hover" %>
                </div>

                <% fs = minister_document.forward_status %>
                <%  @minister_document_forward_department = MinisterDocumentForwardDepartment
        .where(natdirectorate_id: @natdirectorate_id, minister_document_id: minister_document.id) %>

                  <% if current_user&.operator_dn? %>
                      <% if !@minister_document_forward_department.present?  %>
                        <%= link_to "  ", new_minister_document_forward_department_path(doc_id: minister_document.id), class:"bi bi-share-fill btn btn-sm btn-outline-secondary menu-hover" %>
                    <% end %>
                  <% end %>
               
              </div>
          </td>
             
            
        </tr>
      <% end %>
      </tbody>
    </table>


    <% else %>
      <p>No documents found <%= link_to "Back", dashboard_operator_directorate_path, class:"btn btn-sm btn-outline-secondary menu-hover" %></p>
      
    <% end %>

<%= paginate @minister_documents, class:"pagination" %>
    </div>

  </div>






app/views/dashboard_natdirectorate/show.html.erb
<h1>DashboardNatdirectorate#show</h1>
<p>Find me in app/views/dashboard_natdirectorate/show.html.erb</p>

app/views/dashboard_natdirectorate/view_doc_dg.html.erb
<div class="row mt-2">
  <div class="col-sm-8 mb-3 mb-sm-0">
    <div class="card">
    <h6 class="card-header cardcolor">Document DG</h6>
      <div class="card-body">

           <div id="<%= dom_id @document_from_dg %>">

            <ul class="list-group">
              <li class="list-group-item">
                  <div class=" row">
                    <label class="col-sm-3 col-form-label"><strong>Sender:</strong></label> 
                    <div class="col-sm-7">
                      <%= @document_from_dg.sender %> 
                    </div>
                    <div class="col-sm-2">
                      <span class="badge text-bg-success rounded-pill float-end"><%= @document_from_dg.document_source %></span>
                    </div>
                  </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                    <label class="col-sm-3 col-form-label"><strong>Subject:</strong></label> 
                  <div class="col-sm-9">
                    <%= @document_from_dg.subject %>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                  <label class="col-sm-3 col-form-label"><strong>Reference number:</strong></label> 
                  <div class="col-sm-9">
                    <%= @document_from_dg.reference_number %>
                  </div>
                  </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                  <label class="col-sm-3 col-form-label"><strong>Priority:</strong></label> 
                  <div class="col-sm-9">
                    <%= @document_from_dg.priority %>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                      <label class="col-sm-3 col-form-label"><strong>Category:</strong></label> 
                    <div class="col-sm-9">
                      <%= @document_from_dg.category %>
                    </div>
                  </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                    <label class="col-sm-3 col-form-label"><strong>Status:</strong></label> 
                  <div class="col-sm-9">


                  <% @sts =  @document_from_dg.status.to_i %>
                  <% if @sts == 0 %>
                      <% @status = "<span class='badge rounded-pill bg-danger'>Pending</span>".html_safe %>
                  <% elsif @sts == 100 %>
                      <% @status = "<span class='badge rounded-pill bg-success'>Completed</span>".html_safe %>
                  <% else %>
                      <% @status = "<span class='badge rounded-pill bg-warning'>On Progress</span>".html_safe %>
                  <% end %>

                  <div class="container">
                    <div class="row">
                      <div class="col-md-2">
                        <%= @status %><br>
                      </div>
                      <div class=" col-md-10">
                        <div class="progress mt-2" >
                          <div class="progress-bar bg-success" role="progressbar" style="width: <%= @sts%>%;" aria-valuenow="<%= @sts%>" aria-valuemin="<%= @sts%>" aria-valuemax="100"><%= @sts%>%</div>
                        </div>
                      </div>
                    </div>
                  </div>
                   
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="row">
                    <label class="col-sm-3 col-form-label"><strong>Directorate:</strong></label> 
                  <div class="col-sm-9">
                    <%= @document_from_dg.directorate.dirname %>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                  <div class=" row">
                       <label class="col-sm-3 col-form-label"><strong>Forwarded to:</strong></label> 
                      <div class="col-sm-9">

                     
                      <% fs = @document_from_dg.forwardstatus %>
                      <% 
                         
                         if fs == 'department'
                            fst = 100
                         else 
                            fst = 100
                         end
                       %>
                        <%#= @document_dg_departments.inspect %>

                    <% @document_dg_departments.each do |document_dg_department| %>
                      <div class="position-relative m-4">
                        <div class="progress  " role="progressbar" aria-label="Progress" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="height: 4px;">
                          <div class="progress-bar bg-success" style="width: <%= fst %>%"></div>
                        </div>
                        
                        <span class="position-absolute top-0 start-0 translate-middle  rounded-pill badge text-bg-secondary" ><%= @natdirectorate.natdircode %></span>
                        <span class="position-absolute top-0 start-100  translate-middle  rounded-pill badge text-bg-primary" ><%= document_dg_department.department.depcode %></span>
                      </div>
                      <% end %>
  

                        
                      </div>
                    </div>


              </li>
              <li class="list-group-item">
              <div class=" row">
                   <label class="col-sm-3 col-form-label"><strong>Attachment :</strong></label> 
                  <div class="col-sm-9">
                     <a href="<%= @document_from_dg.attachment_doc_dg.url %>" target="_blank" %>
                      <%= File.basename(@document_from_dg.attachment_doc_dg.file.path) if @document_from_dg.attachment_doc_dg.file %>
                     </a>
                  </div>
                </div>
              </li>
            </ul>
            </div>
              <% if current_user&.operator_dn?  %>
                <% fs = @document_from_dg.forwardstatus %>
                  <% if fs != 'department' %>
                  <%= link_to "Forward", new_document_dg_forward_department_path(doc_id: @document_from_dg.id), class:"btn btn-sm btn-secondary float-end mt-2" %>
                  <% end %>
               <% end %>
      </div>
    </div>
  </div>
  
  <div class="col-sm-4">
      <div class="row">

      <% if @document_from_dg_forward_natdirectorate.present? %>
       <div class="col-sm-12 mb-2">
            <div class="card">
            <h6 class="card-header cardcolor">Remarks from DG</h6>
              <div class="card-body">
              <%= @document_from_dg_forward_natdirectorate.description %>
            </div>
          </div>
          </div>
      <% end%>

      <div class="col-sm-12 mb-2">
        <div class="card">
        <h6 class="card-header cardcolor">Update Status</h6>
          <div class="card-body">
             <% @doc_id = DocumentFromDg.find(params[:id])%>
                   <%= form_with(model: @doc_id) do |form| %>
                    <div class="input-group input-group-sm mb-3">
                      <span class="input-group-text" id="inputGroup-sizing-sm">Status</span>
                      <%= form.select :status, DocumentFromDg.statuses.keys.map {|status| [status.humanize, status]},{}, {class:"form-select form-select-sm",  aria_label:"Sizing example input", aria_describedby:"inputGroup-sizing-sm"} %>                    
                       <%= form.submit "Update", class:"btn btn-sm btn-secondary menu-hover" %>
                      </div>

                  <% end %>
        </div>

      </div>
      </div>


      <div class="col-sm-12">
        <div class="card">
        <h6 class="card-header cardcolor">Comments</h6>
          <div class="card-body">
            <%= render 'comment_document_dg/comment', document_from_dg: @document_from_dg %>
            <%= render "comment_document_dg/form", document_from_dg: @document_from_dg %>
        </div>

      </div>
      </div>
  </div>
  </div>


</div>